apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: blue-gree
spec:
  selector:
    app: blue-green-deploy
    version: blue    
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

